name = "rok-manager"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "rok-manager-db"
database_id = "83c35f3b-1706-49ba-bb11-13265418b504"